steps:
- name: node
  entrypoint: yarn
  args: ['install']
- name: node
  entrypoint: yarn
  args: ['build', 'express-cr-app']  
- name: node
  entrypoint: yarn
  args: ['build', 'express-cr-app']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/express-cr-app', '.']
  images: ['gcr.io/$PROJECT_ID/express-cr-app']
  dir: './dist/apps/express-cr-app'